# Generated by Django 3.2.7 on 2021-09-27 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIRCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(max_length=1)),
                ('par', models.CharField(max_length=1)),
                ('int', models.CharField(max_length=1)),
                ('mod', models.IntegerField(validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)])),
                ('val', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PIRDS',
        ),
    ]
