# Generated by Django 3.2.7 on 2021-12-15 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pircs_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('sex', models.CharField(max_length=1)),
                ('resistance', models.FloatField()),
                ('compliance', models.FloatField()),
            ],
        ),
    ]
