# Generated by Django 3.2.7 on 2021-12-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
