# Generated by Django 3.2.7 on 2022-01-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_person_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('TLC', models.FloatField()),
                ('pressure_mouth', models.FloatField()),
                ('resistance', models.FloatField()),
                ('pressure_alveolus', models.FloatField()),
                ('lung_volume', models.FloatField()),
                ('pressure_intrapleural', models.FloatField()),
                ('flow', models.FloatField()),
                ('log', models.JSONField()),
            ],
        ),
    ]
