# Generated by Django 3.2.7 on 2022-01-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patientstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentilatorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField()),
                ('pressure_mouth', models.FloatField()),
                ('mode', models.CharField(max_length=3)),
                ('Pi', models.FloatField()),
                ('PEEP', models.FloatField()),
                ('rate', models.FloatField()),
                ('IE', models.FloatField()),
                ('phase', models.CharField(max_length=1)),
                ('log', models.JSONField()),
                ('time', models.FloatField()),
            ],
        ),
    ]
