# Generated by Django 3.2.7 on 2022-01-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
