# Generated by Django 3.2.7 on 2022-01-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientstate',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='ventilatorstate',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='session',
            name='patientState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientstate'),
        ),
        migrations.AlterField(
            model_name='session',
            name='pircs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pircs'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ventilatorState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ventilatorstate'),
        ),
    ]
