# Generated by Django 3.2.7 on 2022-01-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220117_2154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
