# Generated by Django 3.2.7 on 2022-01-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('patientState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patientstate')),
                ('pircs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pircs')),
                ('ventilatorState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ventilatorstate')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
