# Generated by Django 3.2.7 on 2022-01-17 22:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220117_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('sex', models.CharField(max_length=1)),
                ('resistance', models.FloatField()),
                ('compliance', models.FloatField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.session')),
            ],
        ),
    ]
