# Generated by Django 3.2.7 on 2022-01-17 22:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
