# Generated by Django 3.2.7 on 2022-01-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220117_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
