# Generated by Django 3.2.7 on 2022-01-17 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstate',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
        migrations.AddField(
            model_name='pircs',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
        migrations.AddField(
            model_name='ventilatorstate',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
    ]
